### ISSUE TITLE
Add to Homey appstore?

### ISSUE THREAD

**Issue by mbnn** [StefanPostma/n.vinceste.open-toon#3]
Hello would it be possible to submit this app to the Homey appstore (maybe use a different name)? or call it Open Toon? If not, would you be able to explain how to install it?

**Comment by yustmenl** [comment]
I agree would be nice if we can install it from the store

**Comment by StefanPostma** [comment]
Hi Guys, sorry we cannot add this app because it's almost the same app as the original. There is alot to be rebuild if we want to change this similarities. Also we would like to keep this fork as close to the original App from Athom because we could implement new features build by Athom really fast.

**Comment by Inversion-NL** [comment]
I think that with keeping this app almost the same as the original app, we'll lose some benefits of the Open-Toon.
Like request #2

**Comment by StefanPostma** [comment]
Hi @Inversion-NL i do not agree, adding features can be done without changing the core code. To add it to the homey-store lots of core code needs to be changed, feel free to do so on your own fork of this project ;)
